### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by 15827367876** [langar294/invigilate#1]
可以提供下sql'吗

**Comment by langar294** [comment]
> 

你好，我在新的项目中重写设计了数据库，如果你需要的话，我可以发给你新的

**Comment by langar294** [comment]
你好，我在新的项目中重写设计了数据库，如果你需要的话，我可以发给你新的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 中午11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [langar294/invigilate] sql文件 (Issue #1)





 
可以提供下sql'吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aljj20200526** [comment]
可以发一份sql吗？感恩家人！！如果可以的话，我的邮箱是aljj20200526@163.com

**Comment by langar294** [comment]
> 

已发
